package com.example.ecomerce.service;

import com.example.ecomerce.model.dto.AuthorDTO;
import com.example.ecomerce.model.dto.BookDTO;
import com.example.ecomerce.model.entity.Author;
import com.example.ecomerce.model.entity.Book;
import com.example.ecomerce.repository.AuthorRepository;
import com.example.ecomerce.repository.BookRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;

/**
 * Service can:
 * Call the repository
 * Logic business
 * Convert entities to DTOs
 */

@org.springframework.stereotype.Service
public class Service {
    /**
     * Autowired gets the bean called authorRepository
     * autogenerated by Spring to handle the data.
     */
    @Autowired
    private AuthorRepository authorRepository;

    @Autowired
    private BookRepository bookRepository;

    public @ResponseBody List<AuthorDTO> getAuthorsDTO() {
        return StreamSupport.stream(authorRepository
            .findAll().spliterator(), false)
            .map(Author::toDTO)
            .collect(Collectors.toList());
    }

    @GetMapping("/books")
    public @ResponseBody List<BookDTO> getBooksDTO() {
        return StreamSupport.stream(bookRepository
            .findAll().spliterator(), false)
            .map(Book::toDTO)
            .collect(Collectors.toList());
    }
}
